--- !ruby/object:Jumpstart::Configuration
application_name: Swayed
business_name: Swayed
business_address: ''
domain: imswayed.com
default_from_email: Swayed <support@imswayed.com>
support_email: support@imswayed.com
background_job_processor: sidekiq
email_provider: sendgrid
personal_accounts: false
solargraph: false
register_with_account: true
apns: false
fcm: false
collect_billing_address: true
payment_processors:
- stripe
multitenancy:
- path
